### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Somiona** [DragonsPlusMinecraft/CreateIntegratedFarming#10]
### Minecraft Version

1.21.1

### Describe the Bug

The item "create_integrated_farming:lava_fishing_net" is not activated when Nether Depths Upgrade is not loaded. This will cause an KubeJS internal error which panic about unable to parse the receipe.

### Reproduction Steps

1. Install this mod only, without Nether Depths Upgrade
2. Install Kubejs, add a receipe event process
3. Now you see this bug
...

### Expected Result

Therefore, the receipe json should add "neoforge:conditions" entry to ensure the receipe is not loaded under said condition. 
```json
{
  "neoforge:conditions": [
    {
      "type": "neoforge:mod_loaded",
      "modid": "netherdepthsupgrade"
    }
  ],
  "type": "minecraft:crafting_shaped",
  "category": "misc",
  "key": {
    "#": {
      "item": "minecraft:chain"
    },
    "/": {
      "item": "minecraft:blaze_rod"
    },
    "a": {
      "item": "create:andesite_alloy"
    }
  },
  "pattern": ["###", "##/", "#/a"],
  "result": {
    "count": 2,
    "id": "create_integrated_farming:lava_fishing_net"
  }
}
```

**Comment by MarbleGateKeeper** [comment]
Please upgrade C:IF. This bug has been fixed.

**Comment by Somiona** [comment]
Can confirm the issue persists with 1.0.3 version at both Modrinth and CurseForge, and that is the latest version I can download right now (2025/05/06)

**Comment by MarbleGateKeeper** [comment]
It's in loot table. Loot table datagen do not support condition loading.
Fixed.
